[project]
name = "nextflow-env"
version = "0.1.0"
description = "Add a short description here"
authors = ["dibsondivya <divyashridar14@gmail.com>"]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]
platforms = ["linux-64"]

[tasks]

[dependencies]

[target.linux-64.dependencies]
nextflow = "*"
nf-core = "*"
mamba = "*"
